// ### PROFILE ###
// USERDATA
export const USERDATA_REQUEST = 'USERDATA_REQUEST';
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS';
export const USERDATA_FAILURE = 'USERDATA_FAILURE';
// PROFILE
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
// UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
// DELETE PROFILE
export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_FAILURE = 'DELETE_PROFILE_FAILURE';
// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
// FORGOT PASSWORD
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
// RESET PASSWORD
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
// VERIFY ACCOUNT
export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';
// RESEND VERIFICATION CODE
export const RESEND_CODE_REQUEST = 'RESEND_CODE_REQUEST';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const RESEND_CODE_FAILURE = 'RESEND_CODE_FAILURE';
// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// ### TOURNAMENTS ###
// TOURNAMENTS
export const TOURNAMENTS_REQUEST = 'TOURNAMENTS_REQUEST';
export const TOURNAMENTS_SUCCESS = 'TOURNAMENTS_SUCCESS';
export const TOURNAMENTS_FAILURE = 'TOURNAMENTS_FAILURE';
// TOURNAMENT
export const TOURNAMENT_REQUEST = 'TOURNAMENT_REQUEST';
export const TOURNAMENT_SUCCESS = 'TOURNAMENT_SUCCESS';
export const TOURNAMENT_FAILURE = 'TOURNAMENT_FAILURE';
// JOIN TOURNAMENT
export const JOIN_TOURNAMENT_REQUEST = 'JOIN_TOURNAMENT_REQUEST';
export const JOIN_TOURNAMENT_SUCCESS = 'JOIN_TOURNAMENT_SUCCESS';
export const JOIN_TOURNAMENT_FAILURE = 'JOIN_TOURNAMENT_FAILURE';

export const JOIN_FINALS_TOURNAMENT_REQUEST = 'JOIN_FINALS_TOURNAMENT_REQUEST';
export const JOIN_FINALS_TOURNAMENT_SUCCESS = 'JOIN_FINALS_TOURNAMENT_SUCCESS';
export const JOIN_FINALS_TOURNAMENT_FAILURE = 'JOIN_FINALS_TOURNAMENT_FAILURE';
// OPT OUT
export const OPT_OUT_REQUEST = 'OPT_OUT_REQUEST';
export const OPT_OUT_SUCCESS = 'OPT_OUT_SUCCESS';
export const OPT_OUT_FAILURE = 'OPT_OUT_FAILURE';
// TOURNAMENT POINTS
export const TOURNAMENT_POINTS_REQUEST = 'TOURNAMENT_POINTS_REQUEST';
export const TOURNAMENT_POINTS_SUCCESS = 'TOURNAMENT_POINTS_SUCCESS';
export const TOURNAMENT_POINTS_FAILURE = 'TOURNAMENT_POINTS_FAILURE';

export const FINALS_POINTS_REQUEST = 'FINALS_POINTS_REQUEST';
export const FINALS_POINTS_SUCCESS = 'FINALS_POINTS_SUCCESS';
export const FINALS_POINTS_FAILURE = 'FINALS_POINTS_FAILURE';
// TOURNAMENT TABLE
export const TOURNAMENT_TABLE_REQUEST = 'TOURNAMENT_TABLE_REQUEST';
export const TOURNAMENT_TABLE_SUCCESS = 'TOURNAMENT_TABLE_SUCCESS';
export const TOURNAMENT_TABLE_FAILURE = 'TOURNAMENT_TABLE_FAILURE';
// GET TOURNAMENT ROUNDS
export const TOURNAMENT_ROUNDS_REQUEST = 'TOURNAMENT_ROUNDS_REQUEST';
export const TOURNAMENT_ROUNDS_SUCCESS = 'TOURNAMENT_ROUNDS_SUCCESS';
export const TOURNAMENT_ROUNDS_FAILURE = 'TOURNAMENT_ROUNDS_FAILURE';

// ### PREDICTIONS ###
// GET FIXTURES
export const FIXTURES_REQUEST = 'FIXTURES_REQUEST';
export const FIXTURES_SUCCESS = 'FIXTURES_SUCCESS';
export const FIXTURES_FAILURE = 'FIXTURES_FAILURE';

export const FINALS_FIXTURE_REQUEST = 'FINALS_FIXTURE_REQUEST';
export const FINALS_FIXTURE_SUCCESS = 'FINALS_FIXTURE_SUCCESS';
export const FINALS_FIXTURE_FAILURE = 'FINALS_FIXTURE_FAILURE';
// PREDICT
export const PREDICT_REQUEST = 'PREDICT_REQUEST';
export const PREDICT_SUCCESS = 'PREDICT_SUCCESS';
export const PREDICT_FAILURE = 'PREDICT_FAILURE';

export const FINALS_PREDICT_REQUEST = 'FINALS_PREDICT_REQUEST';
export const FINALS_PREDICT_SUCCESS = 'FINALS_PREDICT_SUCCESS';
export const FINALS_PREDICT_FAILURE = 'FINALS_PREDICT_FAILURE';
// EDIT PREDICTION
export const EDIT_PREDICTION_REQUEST = 'EDIT_PREDICTION_REQUEST';
export const EDIT_PREDICTION_SUCCESS = 'EDIT_PREDICTION_SUCCESS';
export const EDIT_PREDICTION_FAILURE = 'EDIT_PREDICTION_FAILURE';

// ### LEAGUES ###
// LEAGUES
export const LEAGUES_REQUEST = 'LEAGUES_REQUEST';
export const LEAGUES_SUCCESS = 'LEAGUES_SUCCESS';
export const LEAGUES_FAILURE = 'LEAGUES_FAILURE';
// LEAGUE RANKS
export const LEAGUE_RANKS_REQUEST = 'LEAGUE_RANKS_REQUEST';
export const LEAGUE_RANKS_SUCCESS = 'LEAGUE_RANKS_SUCCESS';
export const LEAGUE_RANKS_FAILURE = 'LEAGUE_RANKS_FAILURE';
// CREATE LEAGUE
export const CREATE_LEAGUE_REQUEST = 'CREATE_LEAGUE_REQUEST';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAILURE = 'CREATE_LEAGUE_FAILURE';
// EDIT LEAGUE
export const EDIT_LEAGUE_REQUEST = 'EDIT_LEAGUE_REQUEST';
export const EDIT_LEAGUE_SUCCESS = 'EDIT_LEAGUE_SUCCESS';
export const EDIT_LEAGUE_FAILURE = 'EDIT_LEAGUE_FAILURE';
// DELETE LEAGUE
export const DELETE_LEAGUE_REQUEST = 'DELETE_LEAGUE_REQUEST';
export const DELETE_LEAGUE_SUCCESS = 'DELETE_LEAGUE_SUCCESS';
export const DELETE_LEAGUE_FAILURE = 'DELETE_LEAGUE_FAILURE';
// JOIN LEAGUE
export const JOIN_LEAGUE_REQUEST = 'JOIN_LEAGUE_REQUEST';
export const JOIN_LEAGUE_SUCCESS = 'JOIN_LEAGUE_SUCCESS';
export const JOIN_LEAGUE_FAILURE = 'JOIN_LEAGUE_FAILURE';
// OPT_OUT LEAGUE
export const OPT_OUT_LEAGUE_REQUEST = 'OPT_OUT_LEAGUE_REQUEST';
export const OPT_OUT_LEAGUE_SUCCESS = 'OPT_OUT_LEAGUE_SUCCESS';
export const OPT_OUT_LEAGUE_FAILURE = 'OPT_OUT_LEAGUE_FAILURE';