// ### PROFILE ###
// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
// CREATE ADMIN ACCOUNT
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';
// EDIT ADMIN ACCOUNT
export const EDIT_ACCOUNT_REQUEST = 'EDIT_ACCOUNT_REQUEST';
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS';
export const EDIT_ACCOUNT_FAILURE = 'EDIT_ACCOUNT_FAILURE';
// DELETE ADMIN ACCOUNT
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
// FORGOT PASSWORD
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
// RESET PASSWORD
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
// VIEW PROFILE DETAILS
export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAILURE = 'PROFILE_DETAILS_FAILURE';
export const PROFILE_DETAILS_RESET = 'PROFILE_DETAILS_RESET';
// ### TOURNAMENTS ###
// FETCH TOURNAMENTS
export const FETCH_TOURNAMENT_REQUEST = 'FETCH_TOURNAMENT_REQUEST';
export const FETCH_TOURNAMENT_SUCCESS = 'FETCH_TOURNAMENT_SUCCESS';
export const FETCH_TOURNAMENT_FAILURE = 'FETCH_TOURNAMENT_FAILURE';
// CREATE TOURNAMENT
export const CREATE_TOURNAMENT_REQUEST = 'CREATE_TOURNAMENT_REQUEST';
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';
export const CREATE_TOURNAMENT_FAILURE = 'CREATE_TOURNAMENT_FAILURE';
// UPDATE TOURNAMENT
export const UPDATE_TOURNAMENT_REQUEST = 'UPDATE_TOURNAMENT_REQUEST';
export const UPDATE_TOURNAMENT_SUCCESS = 'UPDATE_TOURNAMENT_SUCCESS';
export const UPDATE_TOURNAMENT_FAILURE = 'UPDATE_TOURNAMENT_FAILURE';
// DELETE TOURNAMENT
export const DELETE_TOURNAMENT_REQUEST = 'DELETE_TOURNAMENT_REQUEST';
export const DELETE_TOURNAMENT_SUCCESS = 'DELETE_TOURNAMENT_SUCCESS';
export const DELETE_TOURNAMENT_FAILURE = 'DELETE_TOURNAMENT_FAILURE';
// ### TOURNAMENT FIXTURES ###
// FETCH FIXTURES
export const FETCH_FIXTURES_REQUEST = 'FETCH_FIXTURES_REQUEST';
export const FETCH_FIXTURES_SUCCESS = 'FETCH_FIXTURES_SUCCESS';
export const FETCH_FIXTURES_FAILURE = 'FETCH_FIXTURES_FAILURE';
// FETCH FIXTUREs ROUNDS
export const FETCH_FIXTURES_ROUNDS_REQUEST = 'FETCH_FIXTURES_ROUNDS_REQUEST';
export const FETCH_FIXTURES_ROUNDS_SUCCESS = 'FETCH_FIXTURES_ROUNDS_SUCCESS';
export const FETCH_FIXTURES_ROUNDS_FAILURE = 'FETCH_FIXTURES_ROUNDS_FAILURE';
// CREATE FIXTURE
export const CREATE_FIXTURE_REQUEST = 'CREATE_FIXTURE_REQUEST';
export const CREATE_FIXTURE_SUCCESS = 'CREATE_FIXTURE_SUCCESS';
export const CREATE_FIXTURE_FAILURE = 'CREATE_FIXTURE_FAILURE';
// UPDATE FIXTURE
export const UPDATE_FIXTURE_REQUEST = 'UPDATE_FIXTURE_REQUEST';
export const UPDATE_FIXTURE_SUCCESS = 'UPDATE_FIXTURE_SUCCESS';
export const UPDATE_FIXTURE_FAILURE = 'UPDATE_FIXTURE_FAILURE';
// DELETE FIXTURES
export const DELETE_FIXTURE_REQUEST = 'DELETE_FIXTURE_REQUEST';
export const DELETE_FIXTURE_SUCCESS = 'DELETE_FIXTURE_SUCCESS';
export const DELETE_FIXTURE_FAILURE = 'DELETE_FIXTURE_FAILURE';
// ### TOURNAMENT FIXTURES RESULTS ###
export const FIXTURE_RESULTS_REQUEST = 'FIXTURE_RESULTS_REQUEST';
export const FIXTURE_RESULTS_SUCCESS = 'FIXTURE_RESULTS_SUCCESS';
export const FIXTURE_RESULTS_FAILURE = 'FIXTURE_RESULTS_FAILURE';

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';